services:
  ares-ui:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/savo4ka/ares-ui:latest
    container_name: ares-ui
    restart: unless-stopped
    ports:
      - "80:80"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s
    networks:
      - ares-service

networks:
  ares-service:
    name: ares-service
    driver: bridge
    external: true
